### ISSUE TITLE
SortedSetBuilder Doesn't Have a Mechanism To Return The Set

### ISSUE THREAD

**Issue by d80tb7** [benbjohnson/immutable#44]
As far as I can tell, `SortedSetBuilder` doesn't have a mechanism to allow the caller to retrieve the built Set.  I propose adding a method, `func(s SortedSetBuilder[T])()SortedSet[T]` which is analogous to `ListBuilder.List()` and `MapBuilder.Map()` respectively.

Happy to make a PR for this if you think it's useful

**Comment by BarrensZeppelin** [comment]
This is definitely an oversight. Feel free to submit a PR. :)
